NETSIBKM2_WebApp/Models/Province.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NETSIBKM2_WebApp.Models
{
    public class Province
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        
        public Region Region { get; set; }
        [ForeignKey("Region")]
        public int RegionId { get; set; }


    }
}

NETSIBKM2_WebApp/Controllers/ProvinceController.cs
using Jint.Runtime.Debugger;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NETSIBKM2_WebApp.Context;
using NETSIBKM2_WebApp.Models;
using NETSIBKM2_WebApp.Repositories.Data;
using System.Linq;

namespace NETSIBKM2_WebApp.Controllers
{
    public class ProvinceController : Controller
    {
        ProvinceRepository ProvinceRepository;

        public ProvinceController(ProvinceRepository ProvinceRepository)
        {
            this.ProvinceRepository = ProvinceRepository;
        }

        // GET ALL
        // GET
        public IActionResult Index()
        {
            var role = HttpContext.Session.GetString("Role");
            if (role.Equals("Admin"))
            {
                var data = ProvinceRepository.Get();
                return View(data);
            }
            return RedirectToAction("Unauthorized", "ErrorPageController");
        }

        // GET BY ID
        // GET
        public IActionResult Details(int id, Province province)
        {
            //var data = myContext.Provinces.Find(id);
            var data = ProvinceRepository.Get(id, province);
            return View(data);

        }

        // CREATE
        // GET
        public IActionResult Create()
        {
            return View();

        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Province province)
        {
            if (ModelState.IsValid)
            {
                //var data = myContext
                var result = ProvinceRepository.Post(province);
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return View();

        }

        // Edit
        // GET
        public IActionResult Update()
        {
            return View();

        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Province province)
        {
            if (ModelState.IsValid)
            {

                var result = ProvinceRepository.Put(id, province);
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return View();
            }

        // Hapus
        // GET
        public IActionResult Delete(Province province)
        {
            if (ModelState.IsValid)
            {
                //myContext.Provinces.Remove(province);
                var result = ProvinceRepository.Delete(province);
                if (result > 0)
                    return RedirectToAction("Index");
            }
            return View();

        }
    }

}

NETSIBKM2_WebApp/Views/Province/Create.cshtml
@model NETSIBKM2_WebApp.Models.Province

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Province</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" asp-controller="Province">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegionId" class="control-label"></label>
                <select asp-for="RegionId" class="form-control" asp-items="ViewBag.RegionId">
                    <option></option>
                    <option value="1"> Waktu Indonesia Barat</option>
                    <option value="2"> Waktu Indonesia Tengah</option>
                    <option value="3"> Waktu Indonesia Timur</option>
                </select>
                <span asp-validation-for="RegionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success" onclick="return confirm('Apakah yakin ingin menyimpan?');" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NETSIBKM2_WebApp/Views/Province/Index.cshtml
@model IEnumerable<NETSIBKM2_WebApp.Models.Province>

@{
    ViewData["Title"] = "Index";
    Layout = "_AdminLayout";
}

<h1> <b>Index </b></h1>

<p>
    <a class="btn btn-outline-warning" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th> 
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Region.Name)
                </td>
                <td>
                    <a  asp-action="Update">update</a>
                    @*@Html.ActionLink("Update", "Update", new { id = item.Id })*@|
                    @Html.ActionLink("Details", "Details", new { /*id = item.Id*/ })
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

NETSIBKM2_WebApp/Views/Province/Update.cshtml
@model NETSIBKM2_WebApp.Models.Province

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Province</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" method="post" asp-controller="Province">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegionId" class="control-label"></label>
                <select asp-for="RegionId" class="form-control" asp-items="ViewBag.RegionId">
                    <option></option>
                    <option value="1"> Waktu Indonesia Barat</option>
                    <option value="2"> Waktu Indonesia Tengah</option>
                    <option value="3"> Waktu Indonesia Timur</option>
                </select>
                <span asp-validation-for="RegionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-outline-success" onclick="return confirm('Apakah yakin ingin Edit?');" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}